project:
  type: website
  output-dir: docs

website:
  title: "Liza Wood"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research 
      - href: workshops.qmd
        text: Workshops / Tutorials
      - href: teaching.qmd
        text: Teaching 
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/liza-wood/
        aria-label: GitHub

format:
  html:
    theme: styles.scss
    mainfont: 'Jost'
    toc: true