---
pagetitle: CV
title: Liza Wood
---

<style type="text/css">
h1.title, h2.subtitle, h3.subtitle {
  text-align: center;
}
</style>

<center> <i class="fa fa-envelope-square" aria-hidden="true"></i> l.wood3@exeter.ac.uk | [<i class="fa fa-globe" aria-hidden="true"></i> website](https://liza-wood.github.io/)</center>

***

### EDUCATION 

Ph.D., Environmental Policy emphasis in Ecology  <span style="float:right;">2023</span>  
Secondary emphasis: Computational Social Science  
University of California Davis, Davis, CA   

M.Sc., Organic Farming and Food Production Systems                        <span style="float:right;">2015</span>  
Newcastle University, Newcastle upon Tyne, United Kingdom   

M.Sc., Sustainability Science and Policy		            	               <span style="float:right;">2014</span>  
Maastricht University, Maastricht, Netherlands   

B.A., Political Science | B.A., Biology 		             	   	           <span style="float:right;">2013</span>  
Honors College at the College of Charleston, Charleston, SC  

***  

### EMPLOYMENT  

Postdoctoral Research Fellow <span style="float:right;">2023 – present</span>   
University of Exeter, Department of Management -- Sustainable Futures  

Graduate Student Researcher and Teaching Assistant <span style="float:right;">2018 – 2023</span>   
University of California Davis, Center for Environmental Policy & Behavior and DataLab

Assistant Director of First-Year Experience <span style="float:right;">2016 – 2018</span>    
College of Charleston, New Student Programs  

***

### PUBLICATIONS

#### PEER-REVIEW PUBLICATIONS  

Scott, T., Kim, S., **Wood, L.** (2025) Open access, professional popularity, and agency involvement drive science referenced in U.S. EPA regulatory impact analyses from 2000 to 2022. *Regulation & Governance.* [http://doi.org/10.1111/rego.70026](http://doi.org/10.1111/rego.70026)  

**Wood, L.**, Vantaggiato, F.P., Scott, T.A. (2025) Tracing the path of knowledge on ‘environmental governance processes’ for theory-building. *Environmental Policy and Governance*. [https://doi.org/10.1002/eet.2151](https://doi.org/10.1002/eet.2151) 

**Wood, L.**, Lubell, M. (2025) Resource constellations and institutional logics shape network-building processes in the organic seed niche. *Environmental Innovation and Societal Transitions*. [https://doi.org/10.1016/j.eist.2025.100965](https://doi.org/10.1016/j.eist.2025.100965)  

**Wood, L.**, Scott, T. (2022) Transportation agencies as consumers and producers of science: The case of state, regional, and county transportation agencies in California. *Transport Policy 128*. [https://doi.org/10.1016/j.tranpol.2022.08.016](https://doi.org/10.1016/j.tranpol.2022.08.016).   

**Wood, L.**, Lubell, M., Rudnick, J., Khalsa, S.D.S., Tatge, S., Sears, M., Brown, P. (2021) Mandatory information-based policy tools facilitate California farmers’ learning about nitrogen management. *Land Use Policy 114*. [https://doi.org/10.1016/j.landusepol.2021.105923](https://doi.org/10.1016/j.landusepol.2021.105923).    

Rudnick, J., Lubell, M., Khalsa, S.D.S., Tatge, S., **Wood, L.**, Sears, M., Brown, P. (2021). A farm systems approach to the adoption of sustainable nitrogen management practices in California. *Agriculture and Human Values 38*. [https://doi.org/10.1007/s10460-021-10190-5](https://doi.org/10.1007/s10460-021-10190-5).  

#### CONFERENCE PAPERS

**Wood, L.** How public and private innovations shape environmental sustainability: Evidence from a century of plant patents. Research Policy 8th Online Conference for Early Career Researchers (2024).  

**Wood, L.**, Pascucci, S. Entanglements of ecological systems and organizational transformation in the organic seed niche. European Group for Organizational Studies (2024).  

**Wood, L.**, Pascucci, S. Mapping the research landscape of collaborative processes in sustainable business model innovation. King's College London Centre for Sustainable Business Short Paper Workshop: Unlocking pathways for a sustainable future (2024)   

**Wood, L.**, Struthers, C., Scott, T.A., Kim, S. Science politics: How political context shapes public agencies’ use of science in environmental policymaking. Environmental Politics and Governance Conference (2023).  

#### REPORTS         

**Wood, L.**, Pascucci, S., Foppe, A., Ashouri, S., Materia, V., Alerasoul, A. (2024). [How to design sustainable business models: A research integrated protocol](https://zenodo.org/records/14224521). Deliverable 5.1 for InBestSoil: Monetary valuation of soil ecosystem services and creation of initiatives to invest in soil health.  

**Wood, L**. (2022). Assessing the Resilience of the Organic Seed System: A Network Perspective. [Proceedings of the 11th Organic Seed Growers Conference](https://seedalliance.org/wp-content/uploads/2022/03/2022-OSGC-Proceedings-Final.pdf).

Hubbard, K., Zystro, J., & **Wood, L**. (2022). [State of Organic Seed](https://stateoforganicseed.org/state-of-organic-seed-2022/). Port Townsend, Washington. \| Data explorer: <https://organicseed.shinyapps.io/SOSData/>

**Wood, L**., Lubell, M. (2022). [Vina Subbasin Farmer Survey Report](https://www.buttecounty.net/DocumentCenter/View/5316/Agricultural-Irrigation-Efficiency-Study-Report-PDF) \| Data explorer: <https://liza-wood.shinyapps.io/Vina-interactive-survey/>

***

### PRESENTATIONS  

#### CONFERENCE PRESENTATIONS  

Rural Sociological Society Annual Meeting |  Utah USA <span style="float:right;">2025</span>  
European Forum for Studies of Policies for Research and Innovation |  Germany <span style="float:right;">2025</span>   
Research Policy 8th Online Conference for Early Career Researchers | virtual <span style="float:right;">2024</span>  
European Group for Organizational Studies | Italy <span style="float:right;">2024</span>  
Environmental Politics and Governance Conference | United Kingdom, Canada  <span style="float:right;">2023, 2024</span>    
King's College London Centre for Sustainable Business Short Paper Workshop | United Kingdom <span style="float:right;">2024</span>  
International Sustainability Transitions Conference | virtual, Netherlands  <span style="float:right;">2022, 2023</span>    
Conference of Policy Process Research | Colorado USA <span style="float:right;">2023</span>    
Duck Family Workshop on Environmental Politics and Governance | Washington USA <span style="float:right;">2022</span>     
Atlanta Academy on Science and Innovation Policy | Georgia USA  <span style="float:right;">2022</span>     
American Association of Geographers Annual Meeting | virtual <span style="float:right;">2020</span>     
International Association for the Study of the Commons | Peru <span style="float:right;">2019</span>    

#### TALKS, WORKSHOPS, AND DISCUSSANT ROLES 


Politecnico di Bari, Management Group  <span style="float:right;">April 2025</span>    
&nbsp;&nbsp;Invited talk | _Who innovates for climate adaptation? Evidence from plant variety development_   
London Environment and Public Policy Workshop <span style="float:right;">September 2024</span>   
&nbsp;&nbsp;Invited discussant | Panel: Palace politics in climate and environmental governance   
King's College London, Environment and Public Policy   Research Group Seminar <span style="float:right;">January 2024</span>  
&nbsp;&nbsp;Seminar talk | _Tracing the path of knowledge on ‘environmental governance processes’ for theory-building_   
University of California Davis, Data Visualization ECL 290 <span style="float:right;">October 2023</span>  
&nbsp;&nbsp;Invited lecture | [_Interactive data with Shiny flexdashboard_](https://liza-wood.github.io/intro-shiny/)  
University of California Davis, Mexican Graduate Student Association <span style="float:right;">May 2023</span>  
&nbsp;&nbsp;Invited workshop | [_Introduction to the Tidyverse_](https://liza-wood.github.io/tidyverse_intro/) & [_Making websites with Rmd & GitHub_](https://liza-wood.github.io/make_github_webpage/)  
University of California Davis, DataLab Micro-credential Program <span style="float:right;">May 2023</span>  
&nbsp;&nbsp;Invited workshop | [_Network visualization_](https://ucdavisdatalab.github.io/workshop_network_viz/)  
Newcastle University, School of Natural and Environmental Sciences Seminar Series  <span style="float:right;">June 2022</span>  
&nbsp;&nbsp;Invited talk | _Supporting innovation for sustainable agriculture_   
Mars-Wrigley Cacao Research and Development Seminar Series <span style="float:right;">December 2021</span>   
&nbsp;&nbsp;Invited talk | _Mapping the seed innovation system_  
  

***


### TEACHING EXPERIENCE    

#### DATA SCIENCE   

Instructor |  Contracted by California State Water Board   
  [R for Water Resources Data Science](https://r4wrds.netlify.app/) <span style="float:right;">Spring 2023, 2024 & 2025</span>  
  
Teaching Assistant | UC Davis -- UC Davis DataLab   
  IST 8x: [Adventures in Data Science](https://ucdavisdatalab.github.io/adventures_in_data_science/) <span style="float:right;">Winter & Spring 2022 & 2023</span>   
  
Instructor |  UC Davis -- Graduate Group in Ecology  
  ECL 298: [R Data Analysis for Visualization in Science](https://gge-ucd.github.io/R-DAVIS/) <span style="float:right;">Fall 2020, 2021 & 2022</span>    


#### ENVIRONMENTAL AND SUSTAINABILITY SCIENCE  

Teaching Assistant | UC Davis -- Departments of Plant Sciences and Environmental Science and Policy  
  PLS 49: Organic Crop Production Practicum <span style="float:right;">Fall 2019, Spring 2020</span>   
  ESP 10: Current Issues in the Environment <span style="float:right;">Winter 2019</span>  
  
Instructor | UC Davis -- Graduate Group Ecology  
  ECL 290: Science Fiction and Near Futures of Ecology <span style="float:right;">Spring 2020</span>  

Instructor |  College of Charleston -- Department of Environmental and Sustainability Science  
  FYET 177: Sustainable Food in the Foothills of the Andes <span style="float:right;">Spring 2017, 2018 & 2019</span>      
  FYSE 142: Farm to Fork: The Sustainable Food Movement in Charleston <span style="float:right;">Spring 2018</span>    

***

### GRANTS, FELLOWSHIPS & AWARDS  

#### RESEARCH 
University of Exeter Department of Management Seed Funding (£1,000)  <span style="float:right;">2024 – 2025</span>      
USDA Western Sustainable Agriculture Research & Education Graduate Grant ($24,997) <span style="float:right;">2020 – 2022</span>       
UC Davis Henry A. Jastro Student Research Fellowship ($12,450) <span style="float:right;">2019 – 2023</span>      
Fulbright Netherlands Research Award, Semi-finalist  <span style="float:right;">2022</span>      
UC Davis Angela and Theodore Foin Graduate Fellowship ($900) <span style="float:right;">2020 – 2021</span>       
Ford Foundation Fellowship Program, Honorable Mention <span style="float:right;">2020</span>       
Davis Muir Institute Graduate Fellowship ($5,000) <span style="float:right;">2019 – 2020</span>       
College of Charleston Political Science Department, 1st place for Best Paper Award <span style="float:right;">2013</span>      
ASIANetwork/Freeman-Asia Foundation Student-Faculty Fellowship to Thailand ($6,000) <span style="float:right;">2012</span>       
College of Charleston Summer Undergraduate Research with Faculty Grant ($5,000) <span style="float:right;">2011</span>       

#### EDUCATION 
UC Davis Graduate Group in Ecology Fellowship <span style="float:right;">2018 – 2020</span>       
Rotary Foundation Global Grant Scholarship to Newcastle, United Kingdom <span style="float:right;">2014 – 2015</span>       
Fulbright Maastricht University Award to Maastricht, The Netherlands <span style="float:right;">2013 – 2014</span>       
College of Charleston Bishop Robert Smith Award <span style="float:right;">2013</span>      
College of Charleston Biology Outstanding Student in the Major Award <span style="float:right;">2013</span>      
College of Charleston Political Science Outstanding Student in the Major Award <span style="float:right;">2013</span>      
College of Charleston Maggie T. Pennington Scholarship <span style="float:right;">2012-2013</span>       
College of Charleston Alexandria Dengate Scholarship <span style="float:right;">2011-2012</span>        

***

### SERVICE  

Program Committee Member | Atlanta Conference on Science and Innovation Policy <span style="float:right;"> 2025</span>  
[Davis R Users Group](https://d-rug.github.io/) Coordinator | UC Davis <span style="float:right;"> 2021 – 2023</span>  
Ecology Graduate Group Graduate Student Mentor | UC Davis <span style="float:right;">  2019 – 2022</span>   
Data Carpentries Instructor | The Carpentries <span style="float:right;">  2021 – 2022</span>    
Admissions Committee Application Reviewer | UC Davis <span style="float:right;"> 2019 – 2021</span>       
Sustainability Literacy Writing Committee Member | College of Charleston <span style="float:right;"> 2017 – 2018</span>      
Faculty for Sustainable Living Workshop Coordinator | College of Charleston <span style="float:right;"> 2016 – 2018</span>   
Internal Fellowship Interview Panelist | College of Charleston <span style="float:right;"> 2016 – 2017</span>  

Reviewer | _Policy Studies Journal, Society & Natural Resources, Environmental Innovations and Societal Transitions, Frontiers in Agronomy, European Management Review_ 

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-HJX1JG1FCV"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-HJX1JG1FCV');
</script>

