---
pagetitle: CV
title: Liza Wood
output: pdf_document
---

<style type="text/css">
h1.title {
  text-align: center;
}
h3.subtitle {
  text-align: center;
}
</style>

<center> <i class="fa fa-envelope-square" aria-hidden="true"></i> belwood@ucdavis.edu | [<i class="fa fa-globe" aria-hidden="true"></i> website](https://liza-wood.github.io/)</center>

***

#### EDUCATION

Ph.D., Ecology  
Areas of Emphasis: Environmental Policy and Agroecology  <span style="float:right;">2018 – present</span>  
Designated Emphasis: Computational Social Science  
University of California Davis, Davis, CA   

M.Sc., Organic Farming and Food Production Systems                        <span style="float:right;">2015</span>  
Newcastle University, Newcastle upon Tyne, United Kingdom   

M.Sc., Sustainability Science and Policy		            	               <span style="float:right;">2014</span>  
Maastricht University, Maastricht, Netherlands   

B.A., Political Science | B.A., Biology 		             	   	           <span style="float:right;">2013</span>  
Honors College at the College of Charleston, Charleston, SC  

***

<h4>EMPLOYMENT</h4> 

Western Sustainable Agriculture Research & Education Program | Graduate Student Researcher  <span style="float:right;">2021 – present</span>    
University of California, Davis | PI: Professor Mark Lubell  
Analyzing organic seed stakeholder networks to better understand structural drivers of seed innovation system transitions in the United States

3 Revolutions for Future Mobility Program | Graduate Student Researcher  <span style="float:right;">2020 – 2022</span>  
University of California, Davis | PI: Professor Tyler Scott   
Assessed the use of science in transportation policy making using web scraping, string manipulation, and machine learning on policy and planning documents from agencies in California  

CDFA Fertilizer Research and Education Program | Graduate Student Researcher  <span style="float:right;">2019 – 2020</span>    
University of California, Davis | PI: Professor Mark Lubell   
Researched how information-based policy tools in California affect farmer conservation behavior using multivariate regression methods        

Horticulture Innovation Lab & USAID | Graduate Student Researcher  <span style="float:right;">2019</span>	 
University of California, Davis | PI: Dr. Elizabeth Mitcham   
Reviewed the lab’s projects in the context of innovation diffusion theories to glean generalizable findings regarding technology adoption for sustainable international development   

First Year Experience | Assistant Director  <span style="float:right;">2016 – 2018</span>     
College of Charleston | Supervisor: Professor Chris Korey  
Managed student enrollment and advising, course planning, and program data for over 50 courses, and supported student and faculty development workshops  

European Union Healthy Minor Cereals Project | Graduate Student Researcher  <span style="float:right;">2014 – 2015</span>   
Newcastle University | PI: Dr. Carlo Leifert   
Evaluated crop quality of spelt grown under organic intensification strategies in Greece and compared nutritional value of organic and conventional spelt and wheat flour in laboratory assays  

Centre for Integrated assessment & Sustainable Development | Graduate Student Researcher  <span style="float:right;">2013 – 2014</span>  
Maastricht University | PI: Dr. Pieter Glasbergen   
Developed sustainability criteria for climate change adaptation strategies to evaluate four major certification standards and conducted action research with Dutch-based NGO, Solidaridad  

ASIANetwork & Freeman Asia Foundation | Undergraduate Researcher  <span style="float:right;">2012 – 2013</span>    
College of Charleston | PI: Dr. Helen Delfeld  				          		 
Conducted survey research to understand cultural narratives related to rice varieties in NE Thailand and the role of alternative markets in the rice commodity supply chain   

***  

<h4>PEER-REVIEWED PUBLICATIONS</h4>   

**Wood, L.**, Scott, T. (2022) Transportation agencies as consumers and producers of science: The case of state, regional, and county transportation agencies in California. *Transport Policy 128*. https://doi.org/10.1016/j.tranpol.2022.08.016.   

**Wood, L.**, Lubell, M., Rudnick, J., Khalsa, S.D.S., Tatge, S., Sears, M., Brown, P. (2021) Mandatory information-based policy tools facilitate California farmers’ learning about nitrogen management. *Land Use Policy 114*. https://doi.org/10.1016/j.landusepol.2021.105923.    

Rudnick, J., Lubell, M., Khalsa, S.D.S., Tatge, S., **Wood, L.**, Sears, M., Brown, P. (2021). A Farm Systems Approach to the Adoption of Sustainable Nitrogen Management Practices in California. *Agriculture and Human Values 38*. https://doi.org/10.1007/s10460-021-10190-5.  

Wang, J., Baranski, M., Korkut, R., Ashraa Kalee, H., **Wood, L.**, et al. (2021). Performance of Modern and Traditional Spelt Wheat (*Triticum spelta*) Varieties in Rain-Fed and Irrigated,Organic and Conventional Production Systems in a Semi-Arid Environment; Results from Exploratory Field Experiments in Crete, Greece. *Agronomy 11*, 809. https://doi.org/10.3390/agronomy11050890.   

<h4>IN PREPARATION</h4>   

**Wood, L.**, Hubbard, K., Zystro, J. Quantifying drivers of niche innovation success across multiple levels: Attitudes, intermediaries, and funding support organic seed transitions. In preparation for *Agricultural Systems*.

**Wood, L.**, Lubell, M. Mapping regional affinity and multi-scalar networks in the organic seed niche innovation system: An empirical test of the Global Innovation System framework. In preparation for *Environmental Innovation and Societal Transitions.*

**Wood, L.**, Lubell, M. Explaining the actor composition and collaborative structures of a spatially sticky innovation system: a structurally explicit network analysis approach. In preparation for *Research Policy*.

**Wood, L.** Who's the real beneficiary of public innovation? Trends in plant variety development and university technology transfer. In preparation for *Research Policy*. 

<h4>OTHER PUBLICATIONS</h4>  

**Wood, L**. (2022). Assessing the Resilience of the Organic Seed System: A Network Perspective. [Proceedings of the 11th Organic Seed Growers Conference](https://seedalliance.org/wp-content/uploads/2022/03/2022-OSGC-Proceedings-Final.pdf).

Hubbard, K., Zystro, J., & **Wood, L**. (2022). [State of Organic Seed](https://stateoforganicseed.org/state-of-organic-seed-2022/). Port Townsend, Washington. \| Data explorer: <https://organicseed.shinyapps.io/SOSData/>

**Wood, L**., Lubell, M. (2022). [Vina Subbasin Farmer Survey Report](http://www.buttecounty.net/wrcdocs/Reports/SpecialProjects/AgIrrEffSurveyRpt/Ag_Irr_Eff_Survey_Rpt_Final_combined.pdf) \| Data explorer: <https://liza-wood.shinyapps.io/Vina-interactive-survey/>

**Wood, L**. (2013). "Sowing sustainability: Rice commodity pathways, NGOs, and farmers' engagement with alternative agriculture in northeastern Thailand." [Growing Sustainable Communities: A Development Guide for Southeast Asia.](https://books.google.com/books/about/Growing_Sustainable_Communities.html?id=sTtZAQAACAAJ&source=kp_book_description) (pp. 111-151). Ed. Brennan, L. et al. Australia: Tilde University Press.
***

<h4>PRESENTATIONS</h4>  

**Wood, L** & Scott, T.A. (2023, January) [govscienceuseR: Tools for quantifying science in policy](https://liza-wood.github.io/gsp_vignette.html). Conference of Policy Process Research. Denver, CO.  

**Wood, L** & Lubell, M. (2022, November). Analyzing sustainability transitions with innovation system networks: The case of the organic seed system in the United States. International Sustainable Transitions Conference, remote presentation.  

**Wood, L**. (2022, June). “Supporting innovation for sustainable agriculture: The case of the organic seed system in the United States.” Newcastle University School of Natural and Environmental Sciences Seminar Series, invited talk, remote presentation.  

**Wood, L**. (2022, May). “Governing agrobiodiversity: A comparison of regional seed innovation systems as social-ecological networks.” 8th Annual Duck Family Workshop on Environmental Politics and Governance, University of Washington. Seattle, WA.     

**Wood, L**. (2022, March). “Seed innovation systems in the US: The politics of science for  agro-ecological transitions.” Atlanta Academy on Science and Innovation Policy. Atlanta, GA.    

**Wood, L**. (2022, February). [“Assessing the Resilience of the Organic Seed System: A Network Perspective.”](https://www.youtube.com/watch?v=1JPhxxy9KeM) Organic Seed Growers Conference, remote presentation.  

**Wood, L**. (2021, December). “Mapping the seed innovation system.” Mars-Wrigley Cacao Research &  Development Seminar Series. Davis, CA.  

**Wood, L**. & Rudnick, J. (2020, April). “The effect of information-based policy tools on farmers’ nitrogen management.” American Association of Geographers Annual Meeting, remote presentation.    

**Wood, L**. (2019, July). “Assessing Seed System Resilience: A Case Study from Northeastern Thailand.” International Association for the Study of the Commons, Lima, Peru.  

Korey, C., **Wood, L**. & Warnick, C. (2017, October). “FYEvolution: Multiple Transitions Revealed Through Student Voice Assessment.” Students in Transition, Costa Mesa, CA.  

Korey, C. & **Wood, L**. (2017, February). “Life So Far – Student Voice as an Assessment Tool.” First-Year Experience Conference, Atlanta, GA.  

**Wood, L**. & Delfeld, H. (2012, September). “Non-governmental agricultural movements and rice commodity systems.” 2nd Workshop on Anticommodities: Local Forms Of Production As Resistance Against Market Domination, Wageningen, The Netherlands.  

***

<h4>TEACHING EXPERIENCE</h4>  

<h5>DATA SCIENCE AND METHODS</h5>  

Instructor |  Contracted by California State Water Board   
  R for Water Resources Data Science <span style="float:right;">Spring 2023</span>  
  
Teaching Assistant | UC Davis -- UC Davis DataLab   
  IST 8x: Adventures in Data Science <span style="float:right;">Winter & Spring 2022</span>   
  
Instructor |  UC Davis -- Graduate Group in Ecology  
  ECL 298: R Data Analysis for Visualization in Science <span style="float:right;">Fall 2020, 2021 & 2022</span>    
  

<h5>ENVIRONMENTAL AND SUSTAINABILITY SCIENCE</h5>   
Teaching Assistant | UC Davis -- Departments of Plant Sciences and Environmental Science and Policy  
  PLS 49: Organic Crop Production Practicum <span style="float:right;">Fall 2019, Spring 2020</span>   
  ESP 10: Current Issues in the Environment <span style="float:right;">Winter 2019</span>  

Instructor |  College of Charleston -- Department of Environmental and Sustainability Science  
  FYET 177: Sustainable Food in the Foothills of the Andes <span style="float:right;">Spring 2017, 2018 & 2019</span>      
  FYSE 142: Farm to Fork: The Sustainable Food Movement in Charleston <span style="float:right;">Spring 2018</span>    

***

<h4>OTHER PROFESSIONAL EXPERIENCE</h4>  

Research Consultant | Environmental Social Research Analysis LLC <span style="float:right;">2020 – 2021</span>   
Climate Change & Agricultural Adaptation Intern | Solidaridad Network <span style="float:right;">2013 – 2014</span>  
Climate & Fisheries Extension Researcher | SC Sea Grant Consortium <span style="float:right;">2012 – 2013</span>  

***

<h4>SELECTED FELLOWSHIPS & AWARDS</h4>
UC Davis Henry A. Jastro Student Research Fellowship  <span style="float:right;"> 2019 – 2023</span>  
Fulbright Netherlands Research Award, Semi-finalist   <span style="float:right;"> 2022</span>   
USDA Western Sustainable Agriculture Research & Education Graduate Student Grant  <span style="float:right;"> 2020 – 2022</span>    
UC Davis Angela and Theodore Foin Graduate Award  <span style="float:right;"> 2020 – 2021</span>     
Ford Foundation Fellowship Program, Honorable Mention <span style="float:right;"> 2020</span>    
UC Davis Muir Institute Graduate Fellowship   <span style="float:right;"> 2019 – 2020</span>    
UC Davis Graduate Group in Ecology Fellowship  <span style="float:right;"> 2018 – 2020</span>      
Rotary Foundation Global Grant Scholarship to Newcastle, United Kingdom  <span style="float:right;"> 2014 – 2015</span>      
Fulbright Maastricht University Award to Maastricht, The Netherlands  <span style="float:right;"> 2013 – 2014</span>     
College of Charleston Political Science Departmental Honors <span style="float:right;"> 2013</span>      
College of Charleston Political Science Department, 1st place for Best Paper Award <span style="float:right;"> 2013</span>     
ASIANetwork Student-Faculty Fellowship to Isaan, Thailand  <span style="float:right;"> 2012</span>    

***

<h4>SERVICE</h4>
  
[Davis R Users Group](https://d-rug.github.io/) Coordinator | UC Davis <span style="float:right;">2021 – present</span>    
Data Carpentries Instructor | The Carpentries <span style="float:right;">2021 – present</span>    
Admissions Committee Application Reviewer | UC Davis <span style="float:right;">2019 – present</span>     
Sustainability Literacy Implementation Committee Member | College of Charleston <span style="float:right;">2017 – 2018</span>     
Faculty for Sustainable Living Workshop Coordinator | College of Charleston <span style="float:right;"> 2016 – 2018</span>    
Student Union Council Representative & Secretary | Newcastle University <span style="float:right;"> 2014 – 2015</span>     
Student Advisory Board Representative | Maastricht University <span style="float:right;">2013 – 2014</span>     

***

<h4>STATISTICAL TRAINING</h4>
Applied Statistical Modeling: Multi-level and Bayesian approaches | UC Davis PLS 298 <span style="float:right;"> 2021</span>    
Introduction to Social and Ecological Network Analysis Short Course | SESYNC  <span style="float:right;"> 2020</span>    
Political Science Quantitative Methods I & II | UC Davis POL 212-213 <span style="float:right;"> 2020</span>     
Algorithmic Reading: Quantitative Text Analysis in R | UC Davis STS 275  <span style="float:right;"> 2020</span>     
Introduction to Computational Social Science | UC Davis CMN 275   <span style="float:right;"> 2019</span>    

<h4>PROGRAMMING LANGUAGES AND SOFTWARE</h4>
R, R Shiny, Qualtrics, Gephi, bash, SQL, Markdown   
