---
title: Liza Wood
author: | 
  | email: l.wood3@exeter.ac.uk | website: https://liza-wood.github.io/
output: pdf_document
urlcolor: blue
header-includes:
  - \usepackage{markdown}
  - \usepackage{lipsum}
---
***

## EDUCATION

Ph.D., Ecology and Environmental Policy    \hfill 2023    
Specialization: Computational Social Science  
University of California Davis, Davis, CA, USA     

M.Sc., Organic Farming and Food Production Systems  \hfill 2015  
Newcastle University, Newcastle upon Tyne, UK    

M.Sc., Sustainability Science and Policy  \hfill 2014    
Maastricht University, Maastricht, NL     

B.A., Political Science | B.A., Biology  \hfill 2013    	
Honors College at the College of Charleston, Charleston, SC, USA    

***

## EMPLOYMENT  

Postdoctoral Research Fellow  \hfill 2023 – present  
University of Exeter, [Environment and Sustainability Institute](https://www.exeter.ac.uk/research/esi/) and [Sustainable Futures](https://business-school.exeter.ac.uk/management/about/sustainable-futures/)  

Graduate Researcher and Teaching Assistant  
University of California Davis   
&nbsp;&nbsp;[DataLab](https://datalab.ucdavis.edu) \hfill 2022 – 2023  
&nbsp;&nbsp;[Center for Environmental Policy & Behavior](https://environmentalpolicy.ucdavis.edu) \hfill 2018 – 2022  
&nbsp;&nbsp;[Horticulture Innovation Lab & USAID](https://horticulture.ucdavis.edu/) \hfill 2019

Assistant Director of First-Year Experience  \hfill 2016 – 2018    
College of Charleston, New Student Programs  

Climate & Fisheries Extension Researcher  \hfill 2012 – 2013  
South Carolina Sea Grant Consortium

***

## FUNDED PROJECTS  

EU Horizon InBestSoil Project | Postdoctoral Researcher \hfill 2023 – present  
University of Exeter   
_Researching collaborative organizational strategies and business models for soil health across nine European case studies; Methods include bibliometric analyses and co-creative activities such as participatory systems mapping_  

Western Sustainable Agriculture Research & Education Program | Graduate Researcher  \hfill 2020 - 2022   
University of California, Davis  
_Analyzed organic seed stakeholder networks to better understand structural drivers of seed innovation system transitions in the United States; Methods included survey design and implementation, regression, and inferential network analysis_  

3 Revolutions for Future Mobility Program | Graduate Researcher  \hfill  2020 – 2022  
University of California, Davis  
_Assessed the use of science in transportation policy making; Methods included web scraping, string manipulation, and machine learning on policy and planning documents from agencies in California _ 

CDFA Fertilizer Research and Education Program | Graduate Researcher \hfill 2019 – 2020   
University of California, Davis  
_Researched how information-based policy tools in California affect farmer conservation behavior; Methods include survey data management and logistic regression_      

Horticulture Innovation Lab & USAID | Graduate Researcher  \hfill 2019  
University of California, Davis   
_Reviewed the Lab’s projects to glean generalizable findings regarding technology adoption for sustainable international development_  

EU Healthy Minor Cereals Project | Graduate Researcher \hfill 2014 – 2015   
Newcastle University   
_Evaluated crop quality of spelt grown under organic intensification strategies in Greece and compared nutritional value of organic and conventional spelt and wheat flour in laboratory assays_  


ASIANetwork & Freeman Asia Foundation | Undergraduate Researcher   \hfill 2012 – 2013    
College of Charleston  		          		 
_Conducted survey research to understand cultural narratives related to rice varieties in NE Thailand and the role of alternative markets in the rice commodity supply chain_   

***  

## PUBLICATIONS

### PEER-REVIEWED PUBLICATIONS  

**Wood, L.**, Scott, T. (2022) Transportation agencies as consumers and producers of science: The case of state, regional, and county transportation agencies in California. *Transport Policy 128*. https://doi.org/10.1016/j.tranpol.2022.08.016.   

**Wood, L.**, Lubell, M., Rudnick, J., Khalsa, S.D.S., Tatge, S., Sears, M., Brown, P. (2021) Mandatory information-based policy tools facilitate California farmers’ learning about nitrogen management. *Land Use Policy 114*. https://doi.org/10.1016/j.landusepol.2021.105923.    

Rudnick, J., Lubell, M., Khalsa, S.D.S., Tatge, S., **Wood, L.**, Sears, M., Brown, P. (2021). A Farm Systems Approach to the Adoption of Sustainable Nitrogen Management Practices in California. *Agriculture and Human Values 38*. https://doi.org/10.1007/s10460-021-10190-5.  

Wang, J., Baranski, M., Korkut, R., Ashraa Kalee, H., **Wood, L.**, et al. (2021). Performance of Modern and Traditional Spelt Wheat (*Triticum spelta*) Varieties in Rain-Fed and Irrigated, Organic and Conventional Production Systems in a Semi-Arid Environment; Results from Exploratory Field Experiments in Crete, Greece. *Agronomy 11*, 809. https://doi.org/10.3390/agronomy11050890.   

### REPORTS & CHAPTER         

Hubbard, K., Zystro, J., & **Wood, L**. (2022). [State of Organic Seed](https://stateoforganicseed.org/state-of-organic-seed-2022/). Port Townsend, Washington. \| Data explorer: <https://organicseed.shinyapps.io/SOSData/>

**Wood, L**., Lubell, M. (2022). [Vina Subbasin Farmer Survey Report](https://www.buttecounty.net/DocumentCenter/View/5316/Agricultural-Irrigation-Efficiency-Study-Report-PDF) \| Data explorer: <https://liza-wood.shinyapps.io/Vina-interactive-survey/>

**Wood, L**. (2013). "Sowing sustainability: Rice commodity pathways, NGOs, and farmers' engagement with alternative agriculture in northeastern Thailand." [Growing Sustainable Communities: A Development Guide for Southeast Asia.](https://books.google.com/books/about/Growing_Sustainable_Communities.html?id=sTtZAQAACAAJ&source=kp_book_description) (pp. 111-151). Ed. Brennan, L. et al. Australia: Tilde University Press. 

### UNDER REVIEW     

**Wood, L.**, Vantaggiato, F.P., Scott, T.A. Tracing the path of knowledge on ‘environmental governance processes’ for theory-building. Revise and resubmit in *Environmental Policy and Governance*.

Scott, T., Kim, S., **Wood, L.** Open access, professional popularity, and agency involvement drive science referenced in U.S. EPA regulatory impact analyses from 2000 to 2022. Revise and resubmit in *Regulation & Governance*.

**Wood, L.**, Lubell, M. Resource constellations and institutional logics shape network-building processes in the organic seed niche. Revise and resubmit in *Environmental Innovation and Societal Transitions*.

**Wood, L.**, Lubell, M. Mapping the spatial structure of the organic seed system: A network approach to the Global Innovation System framework. Under review in *Research Policy*.

***

## PRESENTATIONS  

**Wood, L.** & Pascucci, S. (2024, July) Entanglements of ecological systems and organizational transformation in the organic seed niche. European Group for Organizational Studies. Milan, IT. 

**Wood, L.** (2024, June) How public and private innovations shape environmental sustainability: Evidence from a century of plant patents. Environmental Politics and Governance Conference. Quebec City, CA. 

**Wood, L.**, Pascucci, S. (2024, March) Mapping the research landscape of collaborative processes in sustainable business model innovation. King's College London Centre for Sustainable Business Short Paper Workshop: Unlocking pathways for a sustainable future. London, UK.  

**Wood, L** (2023, August) Sustained coexistence pathways for non-proprietary innovation. International Sustainable Transitions Conference. Utrecht, NL.   

**Wood, L**, Scott, T.A, Struthers, C., Kim, S. (2023, July) Science politics: How political context shapes public agencies’ use of science in environmental policymaking. Environmental Politics and Governance Conference. Glasgow, UK.

**Wood, L** & Lubell, M. (2022, November). Analyzing sustainability transitions with innovation system networks: The case of the organic seed system in the United States. International Sustainable Transitions Conference, remote presentation.  

**Wood, L**. (2022, June). “Supporting innovation for sustainable agriculture: The case of the organic seed system in the United States.” Newcastle University School of Natural and Environmental Sciences Seminar Series, invited talk, remote presentation.  

**Wood, L**. (2022, May). “Governing agrobiodiversity: A comparison of regional seed innovation systems as social-ecological networks.” 8th Annual Duck Family Workshop on Environmental Politics and Governance, University of Washington. Seattle, WA.     

**Wood, L**. (2022, March). “Seed innovation systems in the US: The politics of science for  agro-ecological transitions.” Atlanta Academy on Science and Innovation Policy. Atlanta, GA.    

**Wood, L**. (2022, February). [“Assessing the Resilience of the Organic Seed System: A Network Perspective.”](https://www.youtube.com/watch?v=1JPhxxy9KeM) Organic Seed Growers Conference, remote presentation.  

**Wood, L**. (2021, December). “Mapping the seed innovation system.” Mars-Wrigley Cacao Research &  Development Seminar Series. Davis, CA.  

**Wood, L**. & Rudnick, J. (2020, April). “The effect of information-based policy tools on farmers’ nitrogen management.” American Association of Geographers Annual Meeting, remote presentation.    

**Wood, L**. (2019, July). “Assessing Seed System Resilience: A Case Study from Northeastern Thailand.” International Association for the Study of the Commons, Lima, Peru.  

**Wood, L**. & Delfeld, H. (2012, September). “Non-governmental agricultural movements and rice commodity systems.” 2nd Workshop on Anticommodities: Local Forms Of Production As Resistance Against Market Domination, Wageningen, The Netherlands.  

***

## TEACHING EXPERIENCE   

### ENVIRONMENTAL AND SUSTAINABILITY SCIENCE  

Teaching Assistant | UC Davis -- Departments of Plant Sciences and Environmental Science and Policy  
&nbsp;&nbsp;PLS 49: Organic Crop Production Practicum  \hfill Fall 2019, Spring 2020      
&nbsp;&nbsp;ESP 10: Current Issues in the Environment  \hfill Winter 2019   

Instructor |  College of Charleston -- Department of Environmental and Sustainability Science  
&nbsp;&nbsp;FYET 177: Sustainable Food in the Foothills of the Andes \hfill Spring 2017, 2018 & 2019    
&nbsp;&nbsp;FYSE 142: Farm to Fork: The Sustainable Food Movement in Charleston \hfill Spring 2018  

### DATA SCIENCE   

Instructor |  Contracted by California State Water Board   
&nbsp;&nbsp;[R for Water Resources Data Science](https://www.r4wrds.com/) \hfill Spring 2023, 2024 & 2025  
  
Teaching Assistant | UC Davis -- UC Davis DataLab   
&nbsp;&nbsp;IST 8x: [Adventures in Data Science](https://ucdavisdatalab.github.io/adventures_in_data_science/) \hfill Winter & Spring 2022 & 2023
  
Instructor |  UC Davis -- Graduate Group in Ecology  
&nbsp;&nbsp;ECL 298: [R Data Analysis for Visualization in Science](https://gge-ucd.github.io/R-DAVIS/)  \hfill Fall 2020, 2021 & 2022  

  
***

## GRANTS & AWARDS  

USDA Western Sustainable Agriculture Research & Education Graduate Student Grant \hfill 2020 – 2022   
Rotary Foundation Global Grant Scholarship to Newcastle, United Kingdom \hfill 2014 – 2015   
Fulbright Maastricht University Award to Maastricht, The Netherlands \hfill 2013 – 2014  

## FELLOWSHIPS AND HONORABLE MENTIONS 
Fulbright Netherlands Research Award, Semi-finalist  \hfill 2022  
UC Davis Henry A. Jastro Student Research Fellowship \hfill 2019 – 2023  
UC Davis Angela and Theodore Foin Graduate Fellowship \hfill 2020 – 2021    
Ford Foundation Fellowship Program, Honorable Mention \hfill  2020  
UC Davis Muir Institute Graduate Fellowship \hfill 2019 – 2020   
UC Davis Graduate Group in Ecology Fellowship \hfill 2018 – 2020  
