---
title: Liza Wood
author: | 
  | email: l.wood3@exeter.ac.uk | website: https://liza-wood.github.io/
output: pdf_document
urlcolor: blue
header-includes:
  - \usepackage{markdown}
  - \usepackage{lipsum}
---

_I am a quantitative researcher with a PhD in Environmental Policy and Computational Social Science (fluent in R), seeking a position where I can apply and advance my quantitative and computational skills._ 

***
  
## EDUCATION

Ph.D., Environmental Policy    \hfill 2023    
Specialization: Computational Social Science  
University of California Davis, Davis, CA, USA     

M.Sc., Organic Farming and Food Production Systems  \hfill 2015  
Newcastle University, Newcastle upon Tyne, UK    

M.Sc., Sustainability Science and Policy  \hfill 2014    
Maastricht University, Maastricht, NL     

B.A., Political Science | B.A., Biology  \hfill 2013    	
Honors College at the College of Charleston, Charleston, SC, USA    

***

## EMPLOYMENT  

Postdoctoral Research Fellow  \hfill 2023 – present  
University of Exeter Business School, [Sustainable Futures](https://business-school.exeter.ac.uk/management/about/sustainable-futures/)  

Graduate Student Researcher and Teaching Assistant  
University of California Davis   
&nbsp;&nbsp;[DataLab](https://datalab.ucdavis.edu) \hfill 2022 – 2023  
&nbsp;&nbsp;[Center for Environmental Policy & Behavior](https://environmentalpolicy.ucdavis.edu) \hfill 2018 – 2022  
&nbsp;&nbsp;[Horticulture Innovation Lab & USAID](https://horticulture.ucdavis.edu/) \hfill 2019

Assistant Director of First-Year Experience  \hfill 2016 – 2018    
College of Charleston, New Student Programs  

Climate & Fisheries Extension Researcher  \hfill 2012 – 2013  
South Carolina Sea Grant Consortium

***

## COMPUTATIONAL & STATISTICAL TRAINING 
Applied Statistical Modeling: Multi-level and Bayesian approaches | UC Davis PLS 298 \hfill  2021      
Introduction to Social and Ecological Network Analysis Short Course | SESYNC   \hfill  2020  
Political Science Quantitative Methods I & II | UC Davis POL 212 & 213  \hfill  2020       
Algorithmic Reading: Quantitative Text Analysis in R | UC Davis STS 275   \hfill   2020      
Social Network Analysis Short Course | UC Davis PHR 298 \hfill 2019  
Introduction to Computational Social Science | UC Davis CMN 275    \hfill   2019    

***  

## DATA SCIENCE TEACHING EXPERIENCE   

Instructor |  Contracted by California State Water Board   
&nbsp;&nbsp;[R for Water Resources Data Science](https://www.r4wrds.com/) \hfill Spring 2023, 2024 & 2025  
  
Teaching Assistant | UC Davis -- UC Davis DataLab   
&nbsp;&nbsp;IST 8x: [Adventures in Data Science](https://ucdavisdatalab.github.io/adventures_in_data_science/) \hfill Winter & Spring 2022 & 2023
  
Instructor |  UC Davis -- Graduate Group in Ecology  
&nbsp;&nbsp;ECL 298: [R Data Analysis for Visualization in Science](https://gge-ucd.github.io/R-DAVIS/)  \hfill Fall 2020, 2021 & 2022  
  
***

## PUBLICATIONS

### PEER-REVIEWED PUBLICATIONS  

**Wood, L.**, Scott, T. (2022) Transportation agencies as consumers and producers of science: The case of state, regional, and county transportation agencies in California. *Transport Policy 128*. https://doi.org/10.1016/j.tranpol.2022.08.016.   

**Wood, L.**, Lubell, M., Rudnick, J., Khalsa, S.D.S., Tatge, S., Sears, M., Brown, P. (2021) Mandatory information-based policy tools facilitate California farmers’ learning about nitrogen management. *Land Use Policy 114*. https://doi.org/10.1016/j.landusepol.2021.105923.    


### UNDER REVIEW & IN PREP   

**Wood, L.**, Hubbard, K., Zystro, J. Compliance within regulatory gray areas: The case of the organic seed standard. Revise and resubmit in *Regulation & Governance*.

**Wood, L.**, Vantaggiato, F.P., Scott, T.A. Tracing the path of knowledge on ‘environmental governance processes’ for theory-building. Revise and resubmit in *Environmental Policy and Governance*.

Scott, T., Kim, S., **Wood, L.** Open access, professional popularity, and agency involvement drive science referenced in U.S. EPA regulatory impact analyses from 2000 to 2022. Revise and resubmit in *Regulation & Governance*.

**Wood, L.**, Lubell, M. Mapping the spatial structure of the organic seed system: A network approach to the Global Innovation System framework. Under review in *Research Policy*.

**Wood, L.**, Lubell, M. Resource constellations and institutional logics shape network-building processes in the organic seed niche. Under review in *Environmental Innovation and Societal Transitions*.

**Wood, L.**, Struthers, C., Scott, T.A., Kim, S. Science politics: How political context shapes public agencies’ use of science in environmental policymaking.  

**Wood, L.** How public and private innovations shape environmental sustainability: Evidence from a century of plant patents.  
