---
title: Liza Wood
author: | 
  | email: l.wood3@exeter.ac.uk | website: https://liza-wood.github.io/
output: pdf_document
urlcolor: blue
header-includes:
  - \usepackage{markdown}
  - \usepackage{lipsum}
---

***
  
## EDUCATION

Ph.D., Environmental Policy emphasis in Ecology Graduate Group    \hfill 2023    
Concentration: Computational Social Science  
University of California Davis, Davis, CA, USA     

M.Sc., Organic Farming and Food Production Systems  \hfill 2015  
Newcastle University, Newcastle upon Tyne, UK    

M.Sc., Sustainability Science and Policy  \hfill 2014    
Maastricht University, Maastricht, NL     

B.A., Political Science | B.A., Biology  \hfill 2013    	
Honors College at the College of Charleston, Charleston, SC, USA    

***

## EMPLOYMENT  

Postdoctoral Research Fellow  \hfill 2023 – present  
University of Exeter Business School, [Sustainable Futures](https://business-school.exeter.ac.uk/management/about/sustainable-futures/)  

Graduate Student Researcher and Teaching Assistant  
University of California Davis   
&nbsp;&nbsp;[DataLab](https://datalab.ucdavis.edu) \hfill 2022 – 2023  
&nbsp;&nbsp;[Center for Environmental Policy & Behavior](https://environmentalpolicy.ucdavis.edu) \hfill 2018 – 2022  
&nbsp;&nbsp;[Horticulture Innovation Lab & USAID](https://horticulture.ucdavis.edu/) \hfill 2019

Assistant Director of First-Year Experience  \hfill 2016 – 2018    
College of Charleston, [New Student Programs](https://charleston.edu/first-year-experience/index.php)    
<!---
Climate & Fisheries Extension Researcher  \hfill 2012 – 2013  
South Carolina Sea Grant Consortium
--->

***  
<!---
## VISITING AFFILIATIONS 

Visiting Researcher | Department of Mechanics, Mathematics, and Management, Politecnico di Bari \hfill  April - May 2025 
Associate Fellow | Centre for Sustainable Business, King's College London Business School   \hfill 2024 - 2025 
---> 

## PUBLICATIONS

### PEER-REVIEWED PUBLICATIONS  

Scott, T., Kim, S., **Wood, L.** (2025) Open access, professional popularity, and agency involvement drive science referenced in U.S. EPA regulatory impact analyses from 2000 to 2022. _Regulation & Governance_, http://doi.org/10.1111/rego.70026.      

**Wood, L.**, Vantaggiato, F.P., Scott, T.A. (2025) Tracing the path of knowledge on ‘environmental governance processes’ for theory-building. _Environmental Policy and Governance_, https://doi.org/10.1002/eet.2151. 

**Wood, L.**, Lubell, M. (2025) Resource constellations and institutional logics shape network-building processes in the organic seed niche. _Environmental Innovation and Societal Transitions 55_,  https://doi.org/10.1016/j.eist.2025.100965. 

**Wood, L.**, Scott, T. (2022) Transportation agencies as consumers and producers of science: The case of state, regional, and county transportation agencies in California. *Transport Policy 128*. https://doi.org/10.1016/j.tranpol.2022.08.016.   

**Wood, L.**, Lubell, M., Rudnick, J., Khalsa, S.D.S., Tatge, S., Sears, M., Brown, P. (2021) Mandatory information-based policy tools facilitate California farmers’ learning about nitrogen management. *Land Use Policy 114*. https://doi.org/10.1016/j.landusepol.2021.105923.    

Rudnick, J., Lubell, M., Khalsa, S.D.S., Tatge, S., **Wood, L.**, Sears, M., Brown, P. (2021). A Farm Systems Approach to the Adoption of Sustainable Nitrogen Management Practices in California. *Agriculture and Human Values 38*. https://doi.org/10.1007/s10460-021-10190-5.  

### UNDER REVIEW     

**Wood, L.** Mapping the spatial structure of the organic seed system: A network approach to the Global Innovation System framework. Revise and resubmit in _Research Policy_. 

**Wood, L.**, Zystro, J., Hubbard, K. Compliance in regulatory gray areas: The case of the organic seed standard. Revise and resubmit in _Policy Studies Journal_. 

### CONFERENCE PAPERS

**Wood, L.** How public and private innovations shape environmental sustainability: Evidence from a century of plant patents. Research Policy 8th Online Conference for Early Career Researchers (2024).  

**Wood, L.**, Pascucci, S. Entanglements of ecological systems and organizational transformation in the organic seed niche. European Group for Organizational Studies (2024).  

**Wood, L.**, Pascucci, S. Mapping the research landscape of collaborative processes in sustainable business model innovation. King's College London Centre for Sustainable Business Short Paper Workshop: Unlocking pathways for a sustainable future (2024)   

**Wood, L.**, Struthers, C., Scott, T.A., Kim, S. Science politics: How political context shapes public agencies’ use of science in environmental policymaking. Environmental Politics and Governance Conference (2023).  


### REPORTS FOR PRACTITIONERS        

**Wood, L.**, Pascucci, S., Foppe, A., Ashouri, S., Materia, V., Alerasoul, A. (2024). [How to design sustainable business models: A research integrated protocol](https://zenodo.org/records/14224521). Deliverable 5.1 for InBestSoil: Monetary valuation of soil ecosystem services and creation of initiatives to invest in soil health.  

Hubbard, K., Zystro, J., **Wood, L**. (2022). [State of Organic Seed](https://stateoforganicseed.org/state-of-organic-seed-2022/). Port Townsend, Washington. \| Data explorer: <https://organicseed.shinyapps.io/SOSData/>

**Wood, L**. Lubell, M. (2022). [Vina Subbasin Farmer Survey Report](https://www.buttecounty.net/DocumentCenter/View/5316/Agricultural-Irrigation-Efficiency-Study-Report-PDF) \| Data explorer: <https://liza-wood.shinyapps.io/Vina-interactive-survey/>

**Wood, L**. (2013). "Sowing sustainability: Rice commodity pathways, NGOs, and farmers' engagement with alternative agriculture in northeastern Thailand." [Growing Sustainable Communities: A Development Guide for Southeast Asia.](https://books.google.com/books/about/Growing_Sustainable_Communities.html?id=sTtZAQAACAAJ&source=kp_book_description) (pp. 111-151). Ed. Brennan, L. et al. Australia: Tilde University Press. 

***


## PRESENTATIONS  

### CONFERENCE PRESENTATIONS  

European Forum for Studies of Policies for Research and Innovation |  Germany \hfill 2025  
Research Policy 8th Online Conference for Early Career Researchers | virtual \hfill 2024  
European Group for Organizational Studies | Italy \hfill 2024  
Environmental Politics and Governance Conference | United Kingdom, Canada  \hfill 2023, 2024  
King's College London Centre for Sustainable Business Short Paper Workshop | United Kingdom \hfill 2024  
International Sustainability Transitions Conference | virtual, Netherlands  \hfill 2022, 2023  
Conference of Policy Process Research | Colorado USA \hfill 2023  
Duck Family Workshop on Environmental Politics and Governance | Washington USA \hfill 2022   
Atlanta Academy on Science and Innovation Policy | Georgia USA  \hfill 2022   
American Association of Geographers Annual Meeting | virtual \hfill 2020   
International Association for the Study of the Commons | Peru \hfill 2019  

### TALKS, WORKSHOPS, AND DISCUSSANT ROLES 

Politecnico di Bari, Management Group  \hfill April 2025  
&nbsp;&nbsp;Invited talk | _Who innovates for climate adaptation? Evidence from plant variety development_   
London Environment and Public Policy Workshop \hfill September 2024  
&nbsp;&nbsp;Invited discussant | Panel: Palace politics in climate and environmental governance  
University of California Davis, Data Visualization ECL 290 \hfill October 2023  
&nbsp;&nbsp;Invited lecture | [_Interactive data with Shiny flexdashboard_](https://liza-wood.github.io/intro-shiny/)  
University of California Davis, Mexican Graduate Student Association \hfill May 2023  
&nbsp;&nbsp;Invited workshop | [_Introduction to the Tidyverse_](https://liza-wood.github.io/tidyverse_intro/) & [_Making websites with Rmd & GitHub_](https://liza-wood.github.io/make_github_webpage/)  
University of California Davis, DataLab Micro-credential Program \hfill May 2023  
&nbsp;&nbsp;Invited workshop | [_Network visualization_](https://ucdavisdatalab.github.io/workshop_network_viz/)  
Newcastle University, School of Natural and Environmental Sciences Seminar Series  \hfill June 2022  
&nbsp;&nbsp;Invited talk | _Supporting innovation for sustainable agriculture_   
Mars-Wrigley Cacao Research and Development Seminar Series \hfill December 2021   
&nbsp;&nbsp;Invited talk | _Mapping the seed innovation system_  


***

## TEACHING EXPERIENCE   

### DATA SCIENCE   

Instructor |  Contracted by California State Water Board   
&nbsp;&nbsp;[R for Water Resources Data Science](https://r4wrds.netlify.app/) \hfill Spring 2023, 2024 & 2025  
  
Teaching Assistant | UC Davis -- UC Davis DataLab   
&nbsp;&nbsp;IST 8x: [Adventures in Data Science](https://ucdavisdatalab.github.io/adventures_in_data_science/) \hfill Winter & Spring 2022 & 2023
  
Instructor |  UC Davis -- Graduate Group in Ecology  
&nbsp;&nbsp;ECL 298: [R Data Analysis for Visualization in Science](https://gge-ucd.github.io/R-DAVIS/)  \hfill Fall 2020, 2021 & 2022  

### ENVIRONMENTAL AND SUSTAINABILITY SCIENCE  

Teaching Assistant | UC Davis -- Departments of Plant Sciences and Environmental Science and Policy  
&nbsp;&nbsp;PLS 49: Organic Crop Production Practicum  \hfill Fall 2019, Spring 2020      
&nbsp;&nbsp;ESP 10: Current Issues in the Environment  \hfill Winter 2019  

Instructor | UC Davis -- Graduate Group Ecology  
&nbsp;&nbsp;ECL 290: Science Fiction and Near Futures of Ecology \hfill Spring 2020 

Instructor |  College of Charleston -- Department of Environmental and Sustainability Science  
&nbsp;&nbsp;FYET 177: Sustainable Food in the Foothills of the Andes \hfill Spring 2017, 2018 & 2019    
&nbsp;&nbsp;FYSE 142: Farm to Fork: The Sustainable Food Movement in Charleston \hfill Spring 2018  
  
***

## GRANTS, FELLOWSHIPS & AWARDS  

### RESEARCH 
University of Exeter Department of Management Seed Funding (£1,000)  \hfill 2024 – 2025  
USDA Western Sustainable Agriculture Research & Education Graduate Grant ($24,997) \hfill 2020 – 2022   
UC Davis Henry A. Jastro Student Research Fellowship ($12,450) \hfill 2019 – 2023  
Fulbright Netherlands Research Award, Semi-finalist  \hfill 2022  
UC Davis Angela and Theodore Foin Graduate Fellowship ($900) \hfill 2020 – 2021   
Ford Foundation Fellowship Program, Honorable Mention \hfill  2020   
Davis Muir Institute Graduate Fellowship ($5,000) \hfill 2019 – 2020   
College of Charleston Political Science Department, 1st place for Best Paper Award \hfill 2013  
ASIANetwork/Freeman-Asia Foundation Student-Faculty Fellowship to Thailand ($6,000) \hfill  2012   
College of Charleston Summer Undergraduate Research with Faculty Grant ($5,000) \hfill 2011   

### EDUCATION 
UC Davis Graduate Group in Ecology Fellowship \hfill 2018 – 2020   
Rotary Foundation Global Grant Scholarship to Newcastle, United Kingdom \hfill 2014 – 2015   
Fulbright Maastricht University Award to Maastricht, The Netherlands \hfill 2013 – 2014   
College of Charleston Bishop Robert Smith Award \hfill 2013  
College of Charleston Biology Outstanding Student in the Major Award \hfill 2013  
College of Charleston Political Science Outstanding Student in the Major Award \hfill 2013  
College of Charleston Maggie T. Pennington Scholarship \hfill 2012-2013   
College of Charleston Alexandria Dengate Scholarship \hfill 2011-2012    


***   

## SERVICE

Program Committee Member | Atlanta Conference on Science and Innovation Policy \hfill  2025  
Reviewer | _Policy Studies Journal, Society & Natural Resources, Environmental Innovations and Societal Transitions_ \hfill  2023 – 2025  
[Davis R Users Group](https://d-rug.github.io/) Coordinator | UC Davis \hfill  2021 – 2023  
Ecology Graduate Group Graduate Student Mentor | UC Davis  \hfill  2019 – 2022   
Data Carpentries Instructor | The Carpentries \hfill  2021 – 2022    
Admissions Committee Application Reviewer | UC Davis \hfill  2019 – 2021       
Sustainability Literacy Writing Committee Member | College of Charleston \hfill  2017 – 2018      
Faculty for Sustainable Living Workshop Coordinator | College of Charleston \hfill  2016 – 2018   
Internal Fellowship Interview Panelist | College of Charleston \hfill  2016 – 2017 

<!---
***  

## COMPUTATIONAL & STATISTICAL TRAINING 
Applied Statistical Modeling: Multi-level and Bayesian approaches | UC Davis PLS 298 \hfill  2021      
Introduction to Social and Ecological Network Analysis Short Course | SESYNC   \hfill  2020  
Political Science Quantitative Methods I & II | UC Davis POL 212 & 213  \hfill  2020       
Algorithmic Reading: Quantitative Text Analysis in R | UC Davis STS 275   \hfill   2020      
Social Network Analysis Short Course | UC Davis PHR 298 \hfill 2019  
Introduction to Computational Social Science | UC Davis CMN 275    \hfill   2019    
--->