---
pagetitle: Teaching 
title: Teaching 
---
<style type="text/css">
h1.title {
  text-align: center;
}
</style>


*** 

I have seven years of undergraduate and graduate teaching experience across disciplines, leveraging different pedagogical approaches. I specialize in data science and environmental studies courses. 

### Courses

#### Data science

I am passionate about teaching coding and data analysis across disciplines, and have several years' experience leading methods courses. For example:  

* [R Data Analysis for Visualization in Science](https://gge-ucd.github.io/R-DAVIS/): I co-instructed this course for one term (10 weeks) every year between 2020-2022, teaching R programming to over 100 PhD and Master’s students. This course takes students who have no prior experience with programming to an intermediate level of familiarity with R, giving them the skills necessary to manage projects and clean, reshape and visualize data, all to support their independent research projects in environmental and social sciences. (UC Davis, ECL 298)
* [Adventures in Data Science](https://ucdavisdatalab.github.io/adventures_in_data_science/): I worked as a Teaching Assistant for this course, working closely with the Directors of the [DataLab](https://datalab.ucdavis.edu/) to develop and deliver course material to undergraduate students across disciplines. This was a two-part course, where in the first term we trained students from across social sciences and humanities in the basics of programming in bash, git/GitHub, and R. In the second term, students engaged in experiential learning by working in small groups on real-world data projects proposed by faculty across campus. (UC Davis, IST 8x) 
* [R for Water Resources Data Science](https://r4wrds.netlify.app/): I work with the Convole Cooperative to run Introductory and Intermediate R workshops for professionals working at the California State Water Board. 

Beyond formal teaching, I am passionate about fostering inclusive coding communities. For two years (2021-2023), I co-coordinated the [Davis R Users Group (D-RUG)](https://d-rug.github.io/), a weekly working group of graduate students and university staff addressing computational and statistical challenges in R. Through this role and others, I have been invited to lead several workshops on various coding topics, many of which are available on my [workshops page](workshops.html). 

#### Sustainability studies  

I have designed and taught two interdisciplinary courses on food and agriculture, integrating experiential learning through community service and study abroad.  

* Farm to Fork: The Sustainable Food Movement in Charleston: Lectures covered the cultural, political, and environmental challenges and solutions facing food systems in the US, with a focus on local issues. Beyond lectures, students were required 10 hours of community-based learning, during which students engaged in activities along the food chain, from volunteering in local gardens to preparing and distributing food at food banks (CofC, FYSE 148).   
* Sustainable Food in the Foothills of the Andes: This course was built around a study abroad experience, where I led students on a 10-day trip to Peru to engage with communities in the cross hairs of sustainable development dilemmas. We engaged with organizations like CGIAR’s international potato gene bank in Lima and the Compadre coffee cooperative in the central jungle, which allowed students to connect their food systems curriculum to real-world experiences (CofC, FYET 177). 

#### General education 

I have experience as Teaching Assistant (leading discussions and marking) for several introduction and general education courses.

* Organic Crop Production Practicum (UC Davis, PLS 49)  
* Current Issues in the Environment (UC Davis, ESP 10)   
* Introduction to American Studies (UC Davis, AMS 10)  

*** 

### Pedagogy 

I aim to be pedagogically creative, using experiential learning techniques and problem-based learning to create engaged classroom environments.  

Experiential learning – where students engage in real-world projects beyond the classroom setting – has been a corner stone of my pedagogical approach. For example in my in my sustainability courses, I worked closely with the College's Center for Civic Engagement to incorporate community-based learning into the curriculum. And in data science courses, my work with the UC Davis DataLab [connected students with research projects](https://datalab.ucdavis.edu/adventures-in-data-science-2/) solicited from faculty across campus. 

In cases where it isn’t reasonable to incorporate experiential learning into course design, I use other engagement techniques. For instance, I use problem-based methods where small groups work through pointed discussion questions or technical challenges to help them connect to the content and to one another. 

Theses approaches were developed and honed during my time as the Assistant Director of First-Year Experience (FYE) at College of Charleston (2016-2018), an academic program dedicated to pedagogy and mentorship for supporting undergraduates transitioning into higher education. In this role I also worked with faculty across departments to study student transitions into higher education, with the accompanying publication below. 

Chaffin, L., C. A. Korey, C. Warnick, and **L. Wood** (2019). Life So Far: A Grounded Theory Analysis of College Student Transitions Through the Sophomore Year. [Journal of The First-Year Experience & Students in Transition](https://www.ingentaconnect.com/content/fyesit/fyesit/2019/00000031/00000002/art00005) 31: 79–93.


<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-HJX1JG1FCV"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-HJX1JG1FCV');
</script>

