---
pagetitle: Workshops & Tutorials
title: Workshops & Tutorials
---

<style type="text/css">
h1.title {
  text-align: center;
}
</style>

***

[Preparing data for social-ecological network analysis with `motifR`](https://liza-wood.github.io/sen_motifr/)  
An overview on preparing social-ecological network for analysis in `motifR` along with the use of basic functions. 

***

[Introduction to `flexdashboard` with interactive data visualiation](https://liza-wood.github.io/intro-shiny/)  
An introduction to making interactive dashboards with `flexdashboard` and Shiny integration. This was a brief lesson designed for the UC Davis Ecology Graduate Group Data Visualization ECL 290. 

***

[Making webpages with Rmd + GitHub](https://liza-wood.github.io/make_github_webpage/)  
An introduction to making web pages with GitHub Pages, with an emphasis on project management and using git from Terminal. This was a workshop designed for the UC Davis Mexican Graduate Student Association.  

***

[Treating text as data with PDFs and regex](https://d-rug.github.io/text-as-data/)  
A brief overview of working with text as data (web scraping, PDF reading, and OCR) and regular expressions (regex) for cleaning messy text data with an emphasis on the `stringr` package. This was a presentation designed for for the Davis R-Users Group mini-workshops.   

***

[Introduction to the Tidyverse](https://liza-wood.github.io/tidyverse_intro/)  
An introductory workshop on essential data cleaning and visualizing pipelines using the tidy workflow. This was a workshop designed for the UC Davis Mexican Graduate Student Association.  

***

[Network visualization with `ggraph`](https://ucdavisdatalab.github.io/workshop_network_viz/)  
An intermediate exploration of network data, including a brief review of storing and managing network data and objects, and a focus on integrating network summaries with visualization according to the grammar of graphics. This workshop was designed for the UC Davis DataLab's micro-credential program.

***

[Webscraping public records with `rvest` + regex intro](https://d-rug.github.io/scrape-public-salary-data/)  
A re-vamp of my first webscraping overview, this lesson demonstrates how to scrape data from public salary database, https://transparentcalifornia.com/. This was a presentation designed for for the Davis R-Users Group mini-workshops.  

***

[Introduction to creating a package with `roxygen2`](https://d-rug.github.io/packages_with_roxygen2/)  
Building off of  the function-writing tutorial, this lesson outlines steps for turning a function into a package using the `roxygen2` package. This was a presentation designed for for the Davis R-Users Group mini-workshops.   
 
*** 

[Real-world function writing](https://d-rug.github.io/realworld_functions_iteration/)   
A brief introduction to function-writing using the case of reading in US Patent Office .csv files and cleaning up the data to demonstrate the usefulness of combining functions and iteration. This was a presentation designed for for the Davis R-Users Group mini-workshops. 
  
*** 

[Converting Evernote notes to markdown files](posts/evernote-to-md.html)  
A quick overview of using the `evernote2md` package in R to convert .enex files from Evernote into more accessible .md files. 


***

[Converting Google Docs to LaTeX template for aggiedown](posts/googledoc-aggiedown.html)  
A workflow for connecting the `aggiedown` dissertation LaTeX template with Google Docs. The point is to allow dissertation-writing in Google Docs with Zotero plug-in with a direct feed into an Rmd and BibTeX format.

*** 

[Ordered logits introduction with `MASS` + `VGAM`](posts/ol_partialprop.html)  
A brief introduction to ordered logits using two different packages in R, reviewing the different model specifications and some of the more advances features of the `VGAM` package, particularly non-proportional and partial proportional models. Example using simulated farmer survey data.  

***

[Sequential ordered logits](posts/ol_sequential.html)  
Advancing on the ordered logit introduction, this provides an overview of the continuation ratio (also called sequential) model to ordered logits that want to analyze a dependent ordinal variable that constitutes sequential stages. Example using simulated farmer survey data.  

*** 

[Introduction to R programming videos](https://www.youtube.com/@lizawood1884/playlists)  
These videos, recorded with co-instructors Christian John, Tyler Scott, and Tara Pozzi, are available from each year of R-DAVIS instruction.  
 
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-HJX1JG1FCV"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-HJX1JG1FCV');
</script>
