---
title: "Untitled"
---

R Selenium

https://www.zenrows.com/blog/rselenium#export-data
https://www.scrapingbee.com/blog/getting-started-with-rselenium/
https://www.geeksforgeeks.org/web-scraping-using-rselenium/


Organix seed database for the European Union.

Selenium is different than standard scraping because it is a 'headless browser' -- you can click through and mimic human activity more readily

# Regular scraping

You don't need to use the browser in fancy ways, you can just take the HTML. Why?


```{r}

```

## Login?


# Clicking through

I find this useful especially if links get redirected
# 'arg' should be one of “xpath”, “css selector”, “id”, “name”, “tag name”, “class name”, “link text”, “partial link text”
https://stackoverflow.com/questions/29831142/how-can-i-click-a-link-in-a-webpage-in-rselenium
?selKeys



# Screenshots

I find R Selenium most useful when dealing with data that is stored behind the site as java, but you don't have APIs.

Examples could be when certificates are posted online: Organix and Integrity are two good examples of this.

How to over come this? It isn't pretty, but... screenshots

## Zooming in/out
https://stackoverflow.com/questions/60139836/zoom-out-of-website-when-using-rselenium-without-changing-page-size-resolution

## Scrolling

https://stackoverflow.com/questions/31901072/scrolling-page-in-rselenium